### ISSUE TITLE
Integration failures

### ISSUE THREAD

**Issue by shederman** [severedsolo/UPFM#10]
A common cause of failures in real rockets are integration issues. In Kerbal terms this be Crossfeed failures.

To do it real justice I’d say their likelyhood depends not on the individual part but rather on the combination of the two parts. If they’re being used together for the first time, then integration failures are more likely.

**Comment by severedsolo** [comment]
Funny you should say this. Coming in 1.4 - Oh scrap will look at the overall vessel reliability when calculating failures rather than taking each part individually

**Comment by severedsolo** [comment]
1.4 is now released
