### ISSUE TITLE
Reintroduce static tests

### ISSUE THREAD

**Issue by severedsolo** [severedsolo/UPFM#11]

**Comment by Beetlecat** [comment]
My bad!!  -- just confirmed that a part gets "tested" status when being run/launched on a pad, but still attached to the launch clamps.

🤕 

can close this issue.

**Comment by severedsolo** [comment]
Closed - I'm more efficient than I thought I was :smile:

**Comment by severedsolo** [comment]
Reopened because on inspecting the code this isn't actually working.

**Comment by Beetlecat** [comment]
And I'm sorry I didn't test beyond just seeing the "tested" flag or not.

I'll do a more deliberate round with a handful of parts if that would be helpful.

**Comment by severedsolo** [comment]
It's fine mate, I was just ribbing you on the forum. I know what the issue is.

**Comment by Beetlecat** [comment]
Fair -- I was just confused not knowing whether I was blind, or something had changed I didn't notice. :)

**Comment by severedsolo** [comment]
And fixed. Turns out we were both right. Static tests were missing from the code, but an object at rest on Kerbin is doing around 7m/s according to the code (rotation of Kerbin maybe?) so parts were automatically getting marked as tested, because I was checking if they were doing more than 1.

**Comment by Beetlecat** [comment]
Oh, that's fantastic. It's all about the frame of reference... ;) Thanks for revisiting it!
