### ISSUE TITLE
Divide by 0 in VAB; possible incorrect calculation of vesselSafetyRating?

### ISSUE THREAD

**Issue by JonnyOThan** [severedsolo/UPFM#16]
Saw a divide by 0 error pop up on DasValdez' stream and went to poke at the code.  Noticed this line that looked fishy.  Shouldn't this be outside of the parts loop?  That's how the similar code in Update() works.

https://github.com/severedsolo/OhScrap/blob/bb5cd379b40853a62441b9a5967c94bdcf415a44/OhScrap/UPFMUtils.cs#L282

**Comment by severedsolo** [comment]
Ah! that's probably what's causing #13 - top man thanks

**Comment by severedsolo** [comment]
And fixed
