### ISSUE TITLE
Engine under-thrust failure does nothing if the engine has no throttle capability

### ISSUE THREAD

**Issue by bfrobin446** [severedsolo/UPFM#23]
If an engine's `minThrust` is equal to its `maxThrust`, it continues to provide full power regardless of thrust limiter setting.

When TestFlight wants an engine to underperform, it uses [SetFuelFlowMult()](https://github.com/KSP-RO/TestFlight/blob/master/TestFlightFailure_EnginePerformanceLoss.cs) or [SetFuelIspMult()](https://github.com/KSP-RO/TestFlight/blob/master/TestFlightFailure_EnginePerformanceLoss.cs). Would it be worth adding those as failure modes in OhScrap, or are non-throttling engines not common enough outside Realism Overhaul?

**Comment by severedsolo** [comment]
Well, as far as I'm aware, there is no such thing as a non throttling LF engine in stock.

Whether it's worth it is another question, and that would be up to @zer0kerbal

**Comment by zer0Kerbal** [comment]
I might be willing, once I become more familiar with the code - would need an issue put into my fork.

**Comment by bfrobin446** [comment]
To be honest, the use case is something I've been working on. I'd like to add throttle limits to my RealFuels Stockalike setup, but I'd rather keep OhScrap than write TestFlight settings for every mod I have that needs them.

Since I'm the one that wants it, why don't I take the first crack at coding the changes to OhScrap, and you can decide whether it's worth merging once you see what the code looks like?

**Comment by zer0Kerbal** [comment]
> 
> 
> To be honest, the use case is something I've been working on. I'd like to add throttle limits to my RealFuels Stockalike setup, but I'd rather keep OhScrap than write TestFlight settings for every mod I have that needs them.
> 
> Since I'm the one that wants it, why don't I take the first crack at coding the changes to OhScrap, and you can decide whether it's worth merging once you see what the code looks like?

am all for this. Even if you get pseudo code rolling - I am new to KSP/C# programming - and my coding skills are rusty as Mater in Cars.

Just kindly move over to the new repo, I can always PR the changes back.
https://github.com/zer0Kerbal/OhScrap/issues

eventually I will want to add partFailure to several of my mods - like SimpleLogistics, MoarKerbals, ODFC, Biomatic, and so many others. :D

**Comment by severedsolo** [comment]
Closing this as dealt with under zer0kerbals repo
