### ISSUE TITLE
Generation Count in Part Menu

### ISSUE THREAD

**Issue by Nightside101010** [severedsolo/UPFM#3]
A little bug I noticed. The Generation count line would be doubled or sometimes more in the inflight part menu.

![screenshot1](https://user-images.githubusercontent.com/20480557/26992496-c5983898-4d13-11e7-816b-727e397833f1.png)

**Comment by severedsolo** [comment]
Not so much a bug as an incomplete feature. It's because one part can have multiple failure modules, so it gets added every time. Eventually that will show you the possible modules that can fail.

It's a good catch though, and I'll leave the issue open so I don't forget.
