### ISSUE TITLE
CKAN Support

### ISSUE THREAD

**Issue by Rockstar04** [severedsolo/UPFM#7]
Now that you've hit the 1.0 milestone and picked a name would you be interested in posting this mod to CKAN?

https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN#github-guide

**Comment by severedsolo** [comment]
CKAN support is on the list of things that will be done shortly, once I sort out the post release bugs

**Comment by severedsolo** [comment]
Once KSP-CKAN/NetKAN/pull/6375 is merged, should be all good.
